name: Ping

on:
    workflow_dispatch:
    schedule:
        - cron: "0/30 * * * *"

jobs:
    ping:
        runs-on: ubuntu-latest
        steps:
            - name: Ping
              run: echo "Hello, world!"
